// src/types/BoardPositionCategories.ts
export const categories = [
  'Algorithms & Data Structures',
  'Programming Languages',
  'Web Development',
  'Data Bases',
  'DevOps & Dev Tools',
  'UNIX system terminal',
];

export const boardPositionCategories: { [key: number]: string } = {
  1: 'Algorithms & Data Structures',
  2: 'Programming Languages',
  3: 'Web Development',
  4: 'Data Bases',
  5: 'DevOps & Dev Tools',
  6: 'UNIX system terminal',
  7: 'Algorithms & Data Structures',
  8: 'Programming Languages',
  9: 'Web Development',
  10: 'Data Bases',
  11: 'DevOps & Dev Tools',
  12: 'UNIX system terminal',
  13: 'Algorithms & Data Structures',
  14: 'Programming Languages',
  15: 'Web Development',
  16: 'Data Bases',
  17: 'DevOps & Dev Tools',
  18: 'UNIX system terminal',
  19: 'Algorithms & Data Structures',
  20: 'Programming Languages',
  21: 'Web Development',
  22: 'Data Bases',
  23: 'DevOps & Dev Tools',
  24: 'UNIX system terminal',
  25: 'Algorithms & Data Structures',
  26: 'Programming Languages',
  27: 'Web Development',
  28: 'Data Bases',
  29: 'DevOps & Dev Tools',
  30: 'UNIX system terminal',
  31: 'Algorithms & Data Structures',
  32: 'Programming Languages',
  33: 'Web Development',
  34: 'Data Bases',
  35: 'DevOps & Dev Tools',
  36: 'UNIX system terminal',
  37: 'Algorithms & Data Structures',
  38: 'Programming Languages',
  39: 'Web Development',
  40: 'Data Bases',
  41: 'DevOps & Dev Tools',
  42: 'UNIX system terminal',
  43: 'Algorithms & Data Structures',
  44: 'Programming Languages',
  45: 'Web Development',
  46: 'Data Bases',
  47: 'DevOps & Dev Tools',
  48: 'UNIX system terminal',
  49: 'Algorithms & Data Structures',
  50: 'Programming Languages',
  51: 'Web Development',
  52: 'Data Bases',
  53: 'DevOps & Dev Tools',
  54: 'UNIX system terminal',
  55: 'Algorithms & Data Structures',
  56: 'Programming Languages',
  57: 'Web Development',
  58: 'Data Bases',
  59: 'DevOps & Dev Tools',
  60: 'UNIX system terminal',
};
