// src/types/BoardPositionCategories.ts
export const categories = [
  'Algorithms & Data Structures',
  'Programming Languages',
  'Web Development',
  'Data Bases',
  'DevOps & Dev Tools',
  'UNIX system terminal',
  'Roulete',
  'Start/End'
];

export const boardPositionCategories: { [key: number]: string } = {
  0: 'Start/End',
  1: 'Start/End',
  2: 'Start/End',
  3: 'Start/End',
  4: 'Start/End',
  5: 'Start/End',
  6: 'Algorithms & Data Structures',
  7: 'Programming Languages',
  8: 'Web Development',
  9: 'Data Bases',
  10: 'DevOps & Dev Tools',
  11: 'Data Bases',
  12: 'UNIX system terminal',
  13: 'Programming Languages',
  14: 'DevOps & Dev Tools',
  15: 'Web Development',
  16: 'DevOps & Dev Tools',
  17: 'Algorithms & Data Structures',
  18: 'UNIX system terminal',
  19: 'Web Development',
  20: 'Programming Languages',
  21: 'Web Development',
  22: 'Data Bases',
  23: 'Algorithms & Data Structures',
  24: 'Programming Languages',
  25: 'UNIX system terminal',
  26: 'Programming Languages',
  27: 'DevOps & Dev Tools',
  28: 'Data Bases',
  29: 'UNIX system terminal',
  30: 'Algorithms & Data Structures',
  31: 'UNIX system terminal',
  32: 'Web Development',
  33: 'DevOps & Dev Tools',
  34: 'Algorithms & Data Structures',
  35: 'Data Bases',
  36: 'Web Development',
  37: 'Roulete',
  38: 'Programming Languages',
  39: 'Web Development',
  40: 'Roulete',
  41: 'Programming Languages',
  42: 'Roulete',
  43: 'Data Bases',
  44: 'DevOps & Dev Tools',
  45: 'Roulete',
  46: 'UNIX system terminal',
  47: 'Roulete',
  48: 'UNIX system terminal',
  49: 'Algorithms & Data Structures',
  50: 'Roulete',
  51: 'Algorithms & Data Structures',
  52: 'Roulete',
  53: 'Web Development',
  54: 'Programming Languages',
  55: 'Roulete',
  56: 'Data Bases',
  57: 'Roulete',
  58: 'DevOps & Dev Tools',
  59: 'Data Bases',
  60: 'Roulete',
  61: 'DevOps & Dev Tools',
  62: 'Roulete',
  63: 'Programming Languages',
  64: 'UNIX system terminal',
  65: 'Roulete',
  66: 'Algorithms & Data Structures',
  67: 'UNIX system terminal',
  68: 'Programming Languages',
  69: 'Algorithms & Data Structures',
  70: 'Data Bases',
  71: 'Web Development',
  72: 'Roulete',
  73: 'Data Bases',
  74: 'Algorithms & Data Structures',
  75: 'UNIX system terminal',
  76: 'Data Bases',
  77: 'DevOps & Dev Tools',
  78: 'Programming Languages',
  79: 'Roulete',
  80: 'UNIX system terminal',
  81: 'Programming Languages',
  82: 'Web Development',
  83: 'UNIX system terminal',
  84: 'Algorithms & Data Structures',
  85: 'DevOps & Dev Tools',
  86: 'Roulete',
  87: 'Programming Languages',
  88: 'Web Development',
  89: 'DevOps & Dev Tools',
  90: 'Programming Languages',
  91: 'UNIX system terminal',
  92: 'Data Bases',
  93: 'Roulete',
  94: 'DevOps & Dev Tools',
  95: 'Data Bases',
  96: 'Algorithms & Data Structures',
  97: 'DevOps & Dev Tools',
  98: 'Web Development',
  99: 'UNIX system terminal',
  100: 'Roulete',
  101: 'Web Development',
  102: 'DevOps & Dev Tools',
  103: 'Data Bases',
  104: 'Web Development',
  105: 'Programming Languages',
  106: 'Algorithms & Data Structures',
  107: 'Roulete',
};
