// src/types/BoardPositionCategories.ts
export const categories = [
  'Algorithms & Data Structures',
  'Programming Languages',
  'Web Development',
  'Data Bases',
  'DevOps & Dev Tools',
  'UNIX system terminal',
  'Roulete'
];

export const boardPositionCategories: { [key: number]: string } = {
  1: 'Algorithms & Data Structures',
  2: 'Programming Languages',
  3: 'Web Development',
  4: 'Data Bases',
  5: 'DevOps & Dev Tools',
  6: 'Data Bases',
  7: 'UNIX system terminal',
  8: 'Programming Languages',
  9: 'DevOps & Dev Tools',
  10: 'Web Development',
  11: 'DevOps & Dev Tools',
  12: 'Algorithms & Data Structures',
  13: 'UNIX system terminal',
  14: 'Web Development',
  15: 'Programming Languages',
  16: 'Web Development',
  17: 'Data Bases',
  18: 'Algorithms & Data Structures',
  19: 'Programming Languages',
  20: 'UNIX system terminal',
  21: 'Programming Languages',
  22: 'DevOps & Dev Tools',
  23: 'Data Bases',
  24: 'UNIX system terminal',
  25: 'Algorithms & Data Structures',
  26: 'UNIX system terminal',
  27: 'Web Development',
  28: 'DevOps & Dev Tools',
  29: 'Algorithms & Data Structures',
  30: 'Data Bases',
  31: 'Web Development',
  32: 'Roulete',
  33: 'Programming Languages',
  34: 'Web Development',
  35: 'Roulete',
  36: 'Programming Languages',
  37: 'Roulete',
  38: 'Data Bases',
  39: 'DevOps & Dev Tools',
  40: 'Roulete',
  41: 'UNIX system terminal',
  42: 'Roulete',
  43: 'UNIX system terminal',
  44: 'Algorithms & Data Structures',
  45: 'Roulete',
  46: 'Programming Languages',
  47: 'Roulete',
  48: 'Web Development',
  49: 'Programming Languages',
  50: 'Roulete',
  51: 'Data Bases',
  52: 'Roulete',
  53: 'DevOps & Dev Tools',
  54: 'Data Bases',
  55: 'Roulete',
  56: 'DevOps & Dev Tools',
  57: 'Roulete',
  58: 'Programming Languages',
  59: 'UNIX system terminal',
  60: 'Roulete',
};
